### ISSUE TITLE
When I try to connect the app to the node I get: "Invalid LNDHub URI"

### ISSUE THREAD

**Issue by tifDev** [getumbrel/umbrel-lightning#32]
When I scan the LNDHub QR code in my bluewallet app, I'm getting "Invalid LNDHub URI".

How can I solve this?

**Comment by jimbrend** [comment]
I believe I've narrowed down this issue to a Tor connection issue from BlueWallet Lightning App for this error

![image](https://github.com/getumbrel/umbrel-lightning/assets/8608634/ee19f549-5b09-4ba3-8d9d-6f8912a9929d)


I was able to test with another user who had Invalid LNDhub URL, 

Restarting lightning, BlueWallet app on iOS and updated it, and restarted BlueWallet and it didn't work

QR code (which copies the HTTP://.onion link) and manually copying the Node URL @onion:port doesn't work 

LNDhub connection also didn't work on mine, nor did mine on theirs



- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
However, my QR code works fine that should paste in this format: 
![image](https://github.com/getumbrel/umbrel-lightning/assets/8608634/d180ae45-405c-4bea-a0cc-14ca29729249)

and in my BlueWallet app and my @onion address also worked that should look like
`XXXXd69@w3bqbinlbiXXXX.onion:9735`

(Make sure when you copy you've selected all and pasted and there are no extra spaces or you get the same error)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 



The difference being I seem to be able to connect fine because in my Tor Settings in BlueWallet Daemon Status shows as "Done" 

![image](https://github.com/getumbrel/umbrel-lightning/assets/8608634/ac4ed458-31ec-484d-a3c8-2d194dfdd233)

While theirs showed NOTINIT which could be one cause of this issue.  They are also not able to Start it.

![image](https://github.com/getumbrel/umbrel-lightning/assets/8608634/d07fc459-3fec-4733-befd-17b6a9723238)


I don't know how to resolve this Tor connection user for the client reliably, they were also connecting from a country who's providers have banned direct access to the Tor network (and there is also a Bitcoin ban there) so this could be the problem. 

If anyone has any other input on this NOTINT or a fix for Invalid LNDHub URL fix please share!  

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 



I would recommend using Tailscale for those interested in using LNDhub as a backend for BlueWallet
(as a note since [BlueWallet had sunsetted custodial features](https://bluewallet.io/sunsetting-lndhub/) it's required to connect to a non-custodial backend to create new lightning wallets, and of course your BlueWallet will use the liquidity of the node you connect to)

Via [installing Tailscale on your Umbrel](https://apps.umbrel.com/app/tailscale) and [the device you're connecting from](https://tailscale.com/download/), be sure to login to Tailscale on Umbrel and you will see it [show up as a "connected" machine in Tailscale](https://login.tailscale.com/admin/machines)

Then toggle Tailscale on to "Active" in the app on your device,

Then you can copy your Tailscale address and add the BlueWallet port for Umbrel to connect successfully with a reliable VPN connection that it provides:

`http://XXX.XX.XXX.XX:3008`

This is the format and you paste into your BlueWallet lightning settings and be sure to click save, you'll then get a nice chime noise and a nice alert: 

![image](https://github.com/getumbrel/umbrel-lightning/assets/8608634/549cda8a-1d80-4b34-b28b-a68586053b60)

**Comment by jimbrend** [comment]
Hey y'all, if still running into this check my post above, try Tailscale and confirm you're not getting the NOTINIT error... 

I will close this for now, feel free to ping me if anything is ongoing
