### ISSUE TITLE
Umbrel lnd channels all offline, unable to connect to node

### ISSUE THREAD

**Issue by sahilc0** [getumbrel/umbrel-lightning#35]
Hi there, not sure what changed but all of a sudden I'm unable to log into Thunderhub, and all my lightning channels are offline.

Here's a debug log - seems like there's some errors at the end. Any idea what could be the issue?
[umbrel-1651027827135-debug.log](https://github.com/getumbrel/umbrel/files/8568337/umbrel-1651027827135-debug.log)

**Not working**
- All channels are offline
- Not able to log into Thunderhub dashboard

**Is working**
- The dashboard is loading fine
- blocks seem to be syncing fine

![image](https://user-images.githubusercontent.com/8256062/165431413-3109b9fc-d98b-439c-8e5a-5364894e1605.png)

**Comment by jimbrend** [comment]
> The `block not found` error doesn't look good, maybe something with bitcoind's block index?

hey @mpnemo please feel free to re-open and ping me if you seen this, 

Or please reach out on any of our support channels https://www.umbrel.com/support

Whenever we seen this recently it's almost always a connection issue with Bitcoin, needing to reindex etc. 

Please also update if getting this error if you hadn't already- many errors like peers.dat are also fixed in Bitcoin Core 25.0 and we can get you on latest umbrelOS version, 

Let us know if you needed anything!
